APP_VERSION_CODE_SOURCE=7112
APP_VERSION_CODE=7202
APP_VERSION_NAME=12.10.6
APP_PACKAGE=com.th3nekit.finegram
APP_VERSION_NAME_FINEGRAM=1.2.1
IS_PRIVATE=false
org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=1g
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=false
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.enableR8.fullMode=true

org.gradle.tooling.parallel=true

android.nonTransitiveRClass=false
android.nonFinalResIds=false
