// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     third_party/jni_zero/jni_generator.py
// For
//     org/webrtc/LibvpxVp9Decoder

#ifndef org_webrtc_LibvpxVp9Decoder_JNI
#define org_webrtc_LibvpxVp9Decoder_JNI

#include <jni.h>

#include "third_party/jni_zero/jni_export.h"
#include "webrtc/sdk/android/src/jni/jni_generator_helper.h"

JNI_ZERO_COMPONENT_BUILD_EXPORT extern const char kClassPath_org_webrtc_LibvpxVp9Decoder[];
const char kClassPath_org_webrtc_LibvpxVp9Decoder[] = "org/webrtc/LibvpxVp9Decoder";

JNI_ZERO_COMPONENT_BUILD_EXPORT std::atomic<jclass> g_org_webrtc_LibvpxVp9Decoder_clazz(nullptr);
#ifndef org_webrtc_LibvpxVp9Decoder_clazz_defined
#define org_webrtc_LibvpxVp9Decoder_clazz_defined
inline jclass org_webrtc_LibvpxVp9Decoder_clazz(JNIEnv* env) {
  return jni_zero::LazyGetClass(env, kClassPath_org_webrtc_LibvpxVp9Decoder,
      &g_org_webrtc_LibvpxVp9Decoder_clazz);
}
#endif

namespace webrtc {
namespace jni {

static jlong JNI_LibvpxVp9Decoder_CreateDecoder(JNIEnv* env);

JNI_BOUNDARY_EXPORT jlong Java_org_webrtc_LibvpxVp9Decoder_nativeCreateDecoder(
    JNIEnv* env,
    jclass jcaller) {
  return JNI_LibvpxVp9Decoder_CreateDecoder(env);
}

static jboolean JNI_LibvpxVp9Decoder_IsSupported(JNIEnv* env);

JNI_BOUNDARY_EXPORT jboolean Java_org_webrtc_LibvpxVp9Decoder_nativeIsSupported(
    JNIEnv* env,
    jclass jcaller) {
  return JNI_LibvpxVp9Decoder_IsSupported(env);
}

}
}

#endif
